# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
test:
  resource: "@BthuillierMainBundle/Controller/DefaultController.php"
  prefix: /test
  type: annotation